### ISSUE TITLE
Doesn't work with Deno v1.26 or beyind

### ISSUE THREAD

**Issue by julianq** [CoryG89/deno-vesync#1]
Title. Current version as of writing is v1.35.3, but there were breaking changes in v1.26.0

Workaround for anyone else who may encounter this:

Install Deno as per instructions on Deno website:

`curl -fsSL https://deno.land/x/install/install.sh | sh`

Then downgrade to v1.25.4:

`deno upgrade --version 1.25.4`

**Comment by CoryG89** [comment]
Thanks for the bug report @julianq. Sorry it took me so long to notice this issue. This should be fixed and working with the latest Deno in the most recent version 1.0.1 that I just published. Please reopen if there are any issues.
